# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-10-10 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='magazyny',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customgroup',
            name='stacje',
            field=models.BooleanField(default=True),
        ),
    ]
