# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DopuszczeniaLegalizacje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_urzadzenia', models.CharField(max_length=100)),
                ('nr_urzadzenia', models.CharField(max_length=50)),
                ('opis_czynnosci', models.CharField(max_length=150)),
                ('jednostka_dozorowa', models.CharField(max_length=50)),
                ('data_ostatniej_czynnosci', models.DateField(blank=True, null=True)),
                ('nr_decyzji', models.CharField(max_length=100)),
                ('data_najblizszej_czynnosci', models.DateField()),
                ('osoba_odpowiedzialna_za_nadzor', models.CharField(max_length=100)),
                ('uwagi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Miejsce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('stacja', 'Stacja Paliw'), ('magazyn', 'Magazyn Paliw'), ('budynek', 'Budynek')], max_length=50)),
                ('nazwa', models.CharField(max_length=100)),
                ('adres', models.CharField(max_length=150)),
                ('telefon', models.CharField(max_length=30)),
                ('created_by', models.CharField(max_length=30)),
                ('grupa', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Obiekt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('stacja', 'Stacja Paliw'), ('magazyn', 'Magazyn Paliw')], max_length=100)),
                ('nazwa', models.CharField(max_length=100)),
                ('lokalizacja', models.CharField(default=None, max_length=100)),
                ('nr', models.CharField(default=None, max_length=100)),
                ('wytyczne', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='ObiektK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('dane_techniczne', models.TextField()),
                ('miejsce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baza.Miejsce')),
            ],
        ),
        migrations.CreateModel(
            name='Przedmiot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('lokalizacja', models.TextField()),
                ('nr', models.CharField(max_length=100)),
                ('wytyczne', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PrzegladyTechniczne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_urzadzenia', models.CharField(max_length=100)),
                ('nr_urzadzenia', models.CharField(max_length=50)),
                ('opis_czynnosci', models.CharField(max_length=150)),
                ('jednostka_kontrolujaca', models.CharField(max_length=50)),
                ('data_ostatniej_czynnosci', models.DateField(blank=True, null=True)),
                ('nr_protokolu', models.CharField(max_length=100)),
                ('data_najblizszej_czynnosci', models.DateField()),
                ('osoba_odpowiedzialna_za_nadzor', models.CharField(max_length=100)),
                ('uwagi', models.TextField()),
                ('obiektk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baza.ObiektK')),
            ],
        ),
        migrations.CreateModel(
            name='Urzadzenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('lokalizacja', models.TextField()),
                ('nr', models.CharField(max_length=100)),
                ('wytyczne', models.TextField()),
                ('obiekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baza.Obiekt')),
            ],
        ),
        migrations.AddField(
            model_name='przedmiot',
            name='urzadzenie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='baza.Urzadzenie'),
        ),
        migrations.AddField(
            model_name='dopuszczenialegalizacje',
            name='obiektk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baza.ObiektK'),
        ),
    ]
