# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-03 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0002_auto_20151209_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiwumDopuszczenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nazwa_urzadzenia', models.CharField(max_length=100)),
                ('nr_urzadzenia', models.CharField(blank=True, max_length=50, null=True)),
                ('opis_czynnosci', models.CharField(max_length=150)),
                ('jednostka_dozorowa', models.CharField(max_length=150)),
                ('data_ostatniej_czynnosci', models.DateField(blank=True, null=True)),
                ('nr_decyzji', models.CharField(blank=True, max_length=100, null=True)),
                ('data_najblizszej_czynnosci', models.DateField()),
                ('osoba_odpowiedzialna_za_nadzor', models.CharField(max_length=100)),
                ('uwagi', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dopuszczenialegalizacje',
            name='jednostka_dozorowa',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='dopuszczenialegalizacje',
            name='nr_decyzji',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dopuszczenialegalizacje',
            name='nr_urzadzenia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dopuszczenialegalizacje',
            name='uwagi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='miejsce',
            name='typ',
            field=models.CharField(choices=[('stacja', 'Stacja Paliw'), ('magazyn', 'Magazyn Paliw')], max_length=50),
        ),
        migrations.AlterField(
            model_name='przegladytechniczne',
            name='jednostka_kontrolujaca',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='przegladytechniczne',
            name='nr_protokolu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='przegladytechniczne',
            name='nr_urzadzenia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='przegladytechniczne',
            name='uwagi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archiwumdopuszczenie',
            name='dopuszczenie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baza.DopuszczeniaLegalizacje'),
        ),
    ]
