# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-12-03 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0004_archiwumprzeglad'),
    ]

    operations = [
        migrations.AddField(
            model_name='dopuszczenialegalizacje',
            name='termin_wykonania_zalecen',
            field=models.DateField(blank=True, null=True),
        ),
    ]
