# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-12-03 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0005_dopuszczenialegalizacje_termin_wykonania_zalecen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dopuszczenialegalizacje',
            name='data_najblizszej_czynnosci',
            field=models.DateField(verbose_name='data najbliższej czynności'),
        ),
        migrations.AlterField(
            model_name='dopuszczenialegalizacje',
            name='data_ostatniej_czynnosci',
            field=models.DateField(blank=True, null=True, verbose_name='data ostatniej czynności'),
        ),
        migrations.AlterField(
            model_name='dopuszczenialegalizacje',
            name='nazwa_urzadzenia',
            field=models.CharField(max_length=100, verbose_name='nazwa urządzenia'),
        ),
        migrations.AlterField(
            model_name='dopuszczenialegalizacje',
            name='nr_urzadzenia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='nr urządzenia'),
        ),
        migrations.AlterField(
            model_name='dopuszczenialegalizacje',
            name='opis_czynnosci',
            field=models.CharField(max_length=150, verbose_name='opis czynności'),
        ),
        migrations.AlterField(
            model_name='dopuszczenialegalizacje',
            name='osoba_odpowiedzialna_za_nadzor',
            field=models.CharField(max_length=100, verbose_name='osoba odpowiedzialna za nadzór'),
        ),
        migrations.AlterField(
            model_name='dopuszczenialegalizacje',
            name='termin_wykonania_zalecen',
            field=models.DateField(blank=True, null=True, verbose_name='termin wykonania zaleceń'),
        ),
    ]
