# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-12-03 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0007_auto_20201203_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dopuszczenialegalizacje',
            name='termin_wykonania_polecenia',
            field=models.DateField(blank=True, null=True, verbose_name='termin wykonania polecenia'),
        ),
    ]
