# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-12-07 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0010_zadanie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dopuszczenialegalizacje',
            name='polecenie',
        ),
        migrations.RemoveField(
            model_name='dopuszczenialegalizacje',
            name='termin_wykonania_polecenia',
        ),
    ]
