# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-12-09 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baza', '0012_auto_20201209_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zadanie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField()),
                ('termin', models.DateField(verbose_name='termin wykonania')),
                ('wykonawca', models.CharField(max_length=150)),
                ('wykonane', models.BooleanField(default=False)),
                ('dopuszczenie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baza.DopuszczeniaLegalizacje')),
            ],
        ),
    ]
