# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-12-10 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zadania', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zadanie',
            name='tresc',
            field=models.TextField(verbose_name='treść'),
        ),
        migrations.AlterField(
            model_name='zadanie',
            name='wykonane',
            field=models.BooleanField(default=False, verbose_name='wykonane'),
        ),
        migrations.AlterField(
            model_name='zadanie',
            name='wykonawca',
            field=models.CharField(max_length=150, verbose_name='wykonawca'),
        ),
    ]
