# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-12-13 20:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zadania', '0002_auto_20201210_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='zadanie',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 12, 13, 20, 39, 32, 767612, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zadanie',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2020, 12, 13, 20, 40, 4, 627283, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
