# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-12-03 21:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScopeOfEmailReport',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('stations_reports', models.BooleanField(default=True)),
                ('bases_reports', models.BooleanField(default=True)),
            ],
        ),
    ]
